targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/resource/entity/*.dart
            - lib/resource/state/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/resource/entity/*.dart
            - lib/resource/state/*.dart
        options:
          any_map: true
          explicit_to_json: true
